/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_CMD_DATA_PB_H_INCLUDED
#define PB_CMD_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RunState { 
    RunState_E_STOP = 0, 
    RunState_STOP = 1, 
    RunState_AUTO = 2, 
    RunState_TELEOP = 3 
} RunState;

/* Struct definitions */
typedef struct _Teleop { 
    float leftPower; 
    float rightPower; 
} Teleop;

typedef struct _CmdData { 
    bool has_teleop;
    Teleop teleop; 
    RunState runState; 
} CmdData;


/* Helper constants for enums */
#define _RunState_MIN RunState_E_STOP
#define _RunState_MAX RunState_TELEOP
#define _RunState_ARRAYSIZE ((RunState)(RunState_TELEOP+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Teleop_init_default                      {0, 0}
#define CmdData_init_default                     {false, Teleop_init_default, _RunState_MIN}
#define Teleop_init_zero                         {0, 0}
#define CmdData_init_zero                        {false, Teleop_init_zero, _RunState_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define Teleop_leftPower_tag                     1
#define Teleop_rightPower_tag                    2
#define CmdData_teleop_tag                       1
#define CmdData_runState_tag                     2

/* Struct field encoding specification for nanopb */
#define Teleop_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    leftPower,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    rightPower,        2)
#define Teleop_CALLBACK NULL
#define Teleop_DEFAULT NULL

#define CmdData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  teleop,            1) \
X(a, STATIC,   SINGULAR, UENUM,    runState,          2)
#define CmdData_CALLBACK NULL
#define CmdData_DEFAULT NULL
#define CmdData_teleop_MSGTYPE Teleop

extern const pb_msgdesc_t Teleop_msg;
extern const pb_msgdesc_t CmdData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Teleop_fields &Teleop_msg
#define CmdData_fields &CmdData_msg

/* Maximum encoded size of messages (where known) */
#define CmdData_size                             14
#define Teleop_size                              10

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
