/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_CMD_DATA_PB_H_INCLUDED
#define PB_CMD_DATA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _CmdData_RunState { 
    CmdData_RunState_E_STOP = 0, 
    CmdData_RunState_STOP = 1, 
    CmdData_RunState_AUTO = 2, 
    CmdData_RunState_TELEOP = 3 
} CmdData_RunState;

/* Struct definitions */
typedef struct _CmdData_Teleop { 
    float leftPower; 
    float rightPower; 
} CmdData_Teleop;

typedef struct _CmdData { 
    bool has_teleop;
    CmdData_Teleop teleop; 
    CmdData_RunState runState; 
} CmdData;


/* Helper constants for enums */
#define _CmdData_RunState_MIN CmdData_RunState_E_STOP
#define _CmdData_RunState_MAX CmdData_RunState_TELEOP
#define _CmdData_RunState_ARRAYSIZE ((CmdData_RunState)(CmdData_RunState_TELEOP+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define CmdData_init_default                     {false, CmdData_Teleop_init_default, _CmdData_RunState_MIN}
#define CmdData_Teleop_init_default              {0, 0}
#define CmdData_init_zero                        {false, CmdData_Teleop_init_zero, _CmdData_RunState_MIN}
#define CmdData_Teleop_init_zero                 {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define CmdData_Teleop_leftPower_tag             1
#define CmdData_Teleop_rightPower_tag            2
#define CmdData_teleop_tag                       1
#define CmdData_runState_tag                     2

/* Struct field encoding specification for nanopb */
#define CmdData_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  teleop,            1) \
X(a, STATIC,   SINGULAR, UENUM,    runState,          2)
#define CmdData_CALLBACK NULL
#define CmdData_DEFAULT NULL
#define CmdData_teleop_MSGTYPE CmdData_Teleop

#define CmdData_Teleop_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    leftPower,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    rightPower,        2)
#define CmdData_Teleop_CALLBACK NULL
#define CmdData_Teleop_DEFAULT NULL

extern const pb_msgdesc_t CmdData_msg;
extern const pb_msgdesc_t CmdData_Teleop_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define CmdData_fields &CmdData_msg
#define CmdData_Teleop_fields &CmdData_Teleop_msg

/* Maximum encoded size of messages (where known) */
#define CmdData_Teleop_size                      10
#define CmdData_size                             14

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
