/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_COMMAND_PB_H_INCLUDED
#define PB_COMMAND_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RobotState_State { 
    RobotState_State_E_STOP = 0, 
    RobotState_State_STOP = 1, 
    RobotState_State_RUN = 2 
} RobotState_State;

/* Struct definitions */
typedef struct _RobotState { 
    RobotState_State state_cmd; 
} RobotState;

typedef struct _TeleopCmd { 
    float left_power; 
    float right_power; 
} TeleopCmd;

typedef struct _Command { 
    bool has_teleop_cmd;
    TeleopCmd teleop_cmd; 
    bool has_robot_state;
    RobotState robot_state; 
} Command;


/* Helper constants for enums */
#define _RobotState_State_MIN RobotState_State_E_STOP
#define _RobotState_State_MAX RobotState_State_RUN
#define _RobotState_State_ARRAYSIZE ((RobotState_State)(RobotState_State_RUN+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TeleopCmd_init_default                   {0, 0}
#define RobotState_init_default                  {_RobotState_State_MIN}
#define Command_init_default                     {false, TeleopCmd_init_default, false, RobotState_init_default}
#define TeleopCmd_init_zero                      {0, 0}
#define RobotState_init_zero                     {_RobotState_State_MIN}
#define Command_init_zero                        {false, TeleopCmd_init_zero, false, RobotState_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define RobotState_state_cmd_tag                 1
#define TeleopCmd_left_power_tag                 1
#define TeleopCmd_right_power_tag                2
#define Command_teleop_cmd_tag                   1
#define Command_robot_state_tag                  2

/* Struct field encoding specification for nanopb */
#define TeleopCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    left_power,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    right_power,       2)
#define TeleopCmd_CALLBACK NULL
#define TeleopCmd_DEFAULT NULL

#define RobotState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state_cmd,         1)
#define RobotState_CALLBACK NULL
#define RobotState_DEFAULT NULL

#define Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  teleop_cmd,        1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  robot_state,       2)
#define Command_CALLBACK NULL
#define Command_DEFAULT NULL
#define Command_teleop_cmd_MSGTYPE TeleopCmd
#define Command_robot_state_MSGTYPE RobotState

extern const pb_msgdesc_t TeleopCmd_msg;
extern const pb_msgdesc_t RobotState_msg;
extern const pb_msgdesc_t Command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TeleopCmd_fields &TeleopCmd_msg
#define RobotState_fields &RobotState_msg
#define Command_fields &Command_msg

/* Maximum encoded size of messages (where known) */
#define Command_size                             16
#define RobotState_size                          2
#define TeleopCmd_size                           10

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
