/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_COMMAND_PB_H_INCLUDED
#define PB_COMMAND_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RunState { 
    RunState_E_STOP = 0, 
    RunState_STOP = 1, 
    RunState_RUN = 2 
} RunState;

/* Struct definitions */
typedef struct _Command { 
    /* TeleopCmd teleop_cmd = 1;
 RobotState robot_state = 2; */
    float test; 
} Command;

typedef struct _RobotState { 
    RunState run_state; 
} RobotState;

typedef struct _TeleopCmd { 
    float left_power; 
    float right_power; 
} TeleopCmd;


/* Helper constants for enums */
#define _RunState_MIN RunState_E_STOP
#define _RunState_MAX RunState_RUN
#define _RunState_ARRAYSIZE ((RunState)(RunState_RUN+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define TeleopCmd_init_default                   {0, 0}
#define RobotState_init_default                  {_RunState_MIN}
#define Command_init_default                     {0}
#define TeleopCmd_init_zero                      {0, 0}
#define RobotState_init_zero                     {_RunState_MIN}
#define Command_init_zero                        {0}

/* Field tags (for use in manual encoding/decoding) */
#define Command_test_tag                         1
#define RobotState_run_state_tag                 1
#define TeleopCmd_left_power_tag                 1
#define TeleopCmd_right_power_tag                2

/* Struct field encoding specification for nanopb */
#define TeleopCmd_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    left_power,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    right_power,       2)
#define TeleopCmd_CALLBACK NULL
#define TeleopCmd_DEFAULT NULL

#define RobotState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    run_state,         1)
#define RobotState_CALLBACK NULL
#define RobotState_DEFAULT NULL

#define Command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    test,              1)
#define Command_CALLBACK NULL
#define Command_DEFAULT NULL

extern const pb_msgdesc_t TeleopCmd_msg;
extern const pb_msgdesc_t RobotState_msg;
extern const pb_msgdesc_t Command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define TeleopCmd_fields &TeleopCmd_msg
#define RobotState_fields &RobotState_msg
#define Command_fields &Command_msg

/* Maximum encoded size of messages (where known) */
#define Command_size                             5
#define RobotState_size                          2
#define TeleopCmd_size                           10

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
