/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.5 */

#ifndef PB_POSITION_PB_H_INCLUDED
#define PB_POSITION_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Position { 
    float loc_x; 
    float loc_y; 
    float loc_z; 
    float vel_x; 
    float vel_y; 
    float vel_z; 
    float acc_x; 
    float acc_y; 
    float acc_z; 
    float rot_xy; 
    float rot_xz; 
    float rot_yz; 
} Position;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Position_init_default                    {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Position_init_zero                       {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Position_loc_x_tag                       1
#define Position_loc_y_tag                       2
#define Position_loc_z_tag                       3
#define Position_vel_x_tag                       4
#define Position_vel_y_tag                       5
#define Position_vel_z_tag                       6
#define Position_acc_x_tag                       7
#define Position_acc_y_tag                       8
#define Position_acc_z_tag                       9
#define Position_rot_xy_tag                      10
#define Position_rot_xz_tag                      11
#define Position_rot_yz_tag                      12

/* Struct field encoding specification for nanopb */
#define Position_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FLOAT,    loc_x,             1) \
X(a, STATIC,   REQUIRED, FLOAT,    loc_y,             2) \
X(a, STATIC,   REQUIRED, FLOAT,    loc_z,             3) \
X(a, STATIC,   REQUIRED, FLOAT,    vel_x,             4) \
X(a, STATIC,   REQUIRED, FLOAT,    vel_y,             5) \
X(a, STATIC,   REQUIRED, FLOAT,    vel_z,             6) \
X(a, STATIC,   REQUIRED, FLOAT,    acc_x,             7) \
X(a, STATIC,   REQUIRED, FLOAT,    acc_y,             8) \
X(a, STATIC,   REQUIRED, FLOAT,    acc_z,             9) \
X(a, STATIC,   REQUIRED, FLOAT,    rot_xy,           10) \
X(a, STATIC,   REQUIRED, FLOAT,    rot_xz,           11) \
X(a, STATIC,   REQUIRED, FLOAT,    rot_yz,           12)
#define Position_CALLBACK NULL
#define Position_DEFAULT NULL

extern const pb_msgdesc_t Position_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Position_fields &Position_msg

/* Maximum encoded size of messages (where known) */
#define Position_size                            60

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
