# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cmd_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/cmd_data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14proto/cmd_data.proto\"\xb8\x01\n\x07\x43mdData\x12#\n\x08runState\x18\x01 \x01(\x0e\x32\x11.CmdData.RunState\x12\x1f\n\x06teleop\x18\x02 \x01(\x0b\x32\x0f.CmdData.Teleop\x1a/\n\x06Teleop\x12\x11\n\tleftPower\x18\x01 \x01(\x02\x12\x12\n\nrightPower\x18\x02 \x01(\x02\"6\n\x08RunState\x12\n\n\x06\x45_STOP\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\x08\n\x04\x41UTO\x10\x02\x12\n\n\x06TELEOP\x10\x03\x62\x06proto3'
)



_CMDDATA_RUNSTATE = _descriptor.EnumDescriptor(
  name='RunState',
  full_name='CmdData.RunState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='E_STOP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TELEOP', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=155,
  serialized_end=209,
)
_sym_db.RegisterEnumDescriptor(_CMDDATA_RUNSTATE)


_CMDDATA_TELEOP = _descriptor.Descriptor(
  name='Teleop',
  full_name='CmdData.Teleop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='leftPower', full_name='CmdData.Teleop.leftPower', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rightPower', full_name='CmdData.Teleop.rightPower', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=153,
)

_CMDDATA = _descriptor.Descriptor(
  name='CmdData',
  full_name='CmdData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='runState', full_name='CmdData.runState', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='teleop', full_name='CmdData.teleop', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CMDDATA_TELEOP, ],
  enum_types=[
    _CMDDATA_RUNSTATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=209,
)

_CMDDATA_TELEOP.containing_type = _CMDDATA
_CMDDATA.fields_by_name['runState'].enum_type = _CMDDATA_RUNSTATE
_CMDDATA.fields_by_name['teleop'].message_type = _CMDDATA_TELEOP
_CMDDATA_RUNSTATE.containing_type = _CMDDATA
DESCRIPTOR.message_types_by_name['CmdData'] = _CMDDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CmdData = _reflection.GeneratedProtocolMessageType('CmdData', (_message.Message,), {

  'Teleop' : _reflection.GeneratedProtocolMessageType('Teleop', (_message.Message,), {
    'DESCRIPTOR' : _CMDDATA_TELEOP,
    '__module__' : 'proto.cmd_data_pb2'
    # @@protoc_insertion_point(class_scope:CmdData.Teleop)
    })
  ,
  'DESCRIPTOR' : _CMDDATA,
  '__module__' : 'proto.cmd_data_pb2'
  # @@protoc_insertion_point(class_scope:CmdData)
  })
_sym_db.RegisterMessage(CmdData)
_sym_db.RegisterMessage(CmdData.Teleop)


# @@protoc_insertion_point(module_scope)
