# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cmd_data.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/cmd_data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14proto/cmd_data.proto\"/\n\x06Teleop\x12\x11\n\tleftPower\x18\x01 \x01(\x02\x12\x12\n\nrightPower\x18\x02 \x01(\x02\"?\n\x07\x43mdData\x12\x17\n\x06teleop\x18\x01 \x01(\x0b\x32\x07.Teleop\x12\x1b\n\x08runState\x18\x02 \x01(\x0e\x32\t.RunState*6\n\x08RunState\x12\n\n\x06\x45_STOP\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\x08\n\x04\x41UTO\x10\x02\x12\n\n\x06TELEOP\x10\x03\x62\x06proto3'
)

_RUNSTATE = _descriptor.EnumDescriptor(
  name='RunState',
  full_name='RunState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='E_STOP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AUTO', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TELEOP', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=138,
  serialized_end=192,
)
_sym_db.RegisterEnumDescriptor(_RUNSTATE)

RunState = enum_type_wrapper.EnumTypeWrapper(_RUNSTATE)
E_STOP = 0
STOP = 1
AUTO = 2
TELEOP = 3



_TELEOP = _descriptor.Descriptor(
  name='Teleop',
  full_name='Teleop',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='leftPower', full_name='Teleop.leftPower', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rightPower', full_name='Teleop.rightPower', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=71,
)


_CMDDATA = _descriptor.Descriptor(
  name='CmdData',
  full_name='CmdData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='teleop', full_name='CmdData.teleop', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='runState', full_name='CmdData.runState', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=136,
)

_CMDDATA.fields_by_name['teleop'].message_type = _TELEOP
_CMDDATA.fields_by_name['runState'].enum_type = _RUNSTATE
DESCRIPTOR.message_types_by_name['Teleop'] = _TELEOP
DESCRIPTOR.message_types_by_name['CmdData'] = _CMDDATA
DESCRIPTOR.enum_types_by_name['RunState'] = _RUNSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Teleop = _reflection.GeneratedProtocolMessageType('Teleop', (_message.Message,), {
  'DESCRIPTOR' : _TELEOP,
  '__module__' : 'proto.cmd_data_pb2'
  # @@protoc_insertion_point(class_scope:Teleop)
  })
_sym_db.RegisterMessage(Teleop)

CmdData = _reflection.GeneratedProtocolMessageType('CmdData', (_message.Message,), {
  'DESCRIPTOR' : _CMDDATA,
  '__module__' : 'proto.cmd_data_pb2'
  # @@protoc_insertion_point(class_scope:CmdData)
  })
_sym_db.RegisterMessage(CmdData)


# @@protoc_insertion_point(module_scope)
