# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/command.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/command.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13proto/command.proto\"4\n\tTeleopCmd\x12\x12\n\nleft_power\x18\x01 \x01(\x02\x12\x13\n\x0bright_power\x18\x02 \x01(\x02\"*\n\nRobotState\x12\x1c\n\trun_state\x18\x01 \x01(\x0e\x32\t.RunState\"\x17\n\x07\x43ommand\x12\x0c\n\x04test\x18\x01 \x01(\x02*)\n\x08RunState\x12\n\n\x06\x45_STOP\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\x07\n\x03RUN\x10\x02\x62\x06proto3'
)

_RUNSTATE = _descriptor.EnumDescriptor(
  name='RunState',
  full_name='RunState',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='E_STOP', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=146,
  serialized_end=187,
)
_sym_db.RegisterEnumDescriptor(_RUNSTATE)

RunState = enum_type_wrapper.EnumTypeWrapper(_RUNSTATE)
E_STOP = 0
STOP = 1
RUN = 2



_TELEOPCMD = _descriptor.Descriptor(
  name='TeleopCmd',
  full_name='TeleopCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='left_power', full_name='TeleopCmd.left_power', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='right_power', full_name='TeleopCmd.right_power', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=75,
)


_ROBOTSTATE = _descriptor.Descriptor(
  name='RobotState',
  full_name='RobotState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='run_state', full_name='RobotState.run_state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=119,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='test', full_name='Command.test', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=144,
)

_ROBOTSTATE.fields_by_name['run_state'].enum_type = _RUNSTATE
DESCRIPTOR.message_types_by_name['TeleopCmd'] = _TELEOPCMD
DESCRIPTOR.message_types_by_name['RobotState'] = _ROBOTSTATE
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.enum_types_by_name['RunState'] = _RUNSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeleopCmd = _reflection.GeneratedProtocolMessageType('TeleopCmd', (_message.Message,), {
  'DESCRIPTOR' : _TELEOPCMD,
  '__module__' : 'proto.command_pb2'
  # @@protoc_insertion_point(class_scope:TeleopCmd)
  })
_sym_db.RegisterMessage(TeleopCmd)

RobotState = _reflection.GeneratedProtocolMessageType('RobotState', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTSTATE,
  '__module__' : 'proto.command_pb2'
  # @@protoc_insertion_point(class_scope:RobotState)
  })
_sym_db.RegisterMessage(RobotState)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'proto.command_pb2'
  # @@protoc_insertion_point(class_scope:Command)
  })
_sym_db.RegisterMessage(Command)


# @@protoc_insertion_point(module_scope)
