# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/guidance_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19proto/guidance_data.proto\"\xdb\x04\n\x0cGuidanceData\x12\x0e\n\x06\x64\x65ltaT\x18\x01 \x01(\x02\x12\x13\n\x0bsetpointVel\x18\x02 \x01(\x02\x12\x0b\n\x03vel\x18\x03 \x01(\x02\x12\x0e\n\x06\x65rrVel\x18\x04 \x01(\x02\x12\x0f\n\x07\x65rrVelI\x18\x05 \x01(\x02\x12\x0f\n\x07\x65rrVelD\x18\x06 \x01(\x02\x12\x0e\n\x06kP_vel\x18\x07 \x01(\x02\x12\x0e\n\x06kI_vel\x18\x08 \x01(\x02\x12\x0e\n\x06kD_vel\x18\t \x01(\x02\x12\x0c\n\x04velP\x18\n \x01(\x02\x12\x0c\n\x04velI\x18\x0b \x01(\x02\x12\x0c\n\x04velD\x18\x0c \x01(\x02\x12\x15\n\rleftOutputVel\x18\r \x01(\x02\x12\x16\n\x0erightOutputVel\x18\x0e \x01(\x02\x12\x10\n\x08\x65rrDrift\x18\x0f \x01(\x02\x12\x11\n\terrDriftI\x18\x10 \x01(\x02\x12\x11\n\terrDriftD\x18\x11 \x01(\x02\x12\x10\n\x08kP_drift\x18\x12 \x01(\x02\x12\x10\n\x08kI_drift\x18\x13 \x01(\x02\x12\x10\n\x08kD_drift\x18\x14 \x01(\x02\x12\x0e\n\x06\x64riftP\x18\x15 \x01(\x02\x12\x0e\n\x06\x64riftI\x18\x16 \x01(\x02\x12\x0e\n\x06\x64riftD\x18\x17 \x01(\x02\x12\x17\n\x0fleftOutputDrift\x18\x18 \x01(\x02\x12\x18\n\x10rightOutputDrift\x18\x19 \x01(\x02\x12\x14\n\x0cleftTotalPID\x18\x1a \x01(\x02\x12\x15\n\rrightTotalPID\x18\x1b \x01(\x02\x12\x11\n\tleftPower\x18\x1c \x01(\x02\x12\x12\n\nrightPower\x18\x1d \x01(\x02\x12\x11\n\tpropPower\x18\x1e \x01(\x02\x12\x0e\n\x06segNum\x18\x1f \x01(\r\x12\x16\n\x0e\x63ompletedTrack\x18  \x01(\x08\x62\x06proto3')



_GUIDANCEDATA = DESCRIPTOR.message_types_by_name['GuidanceData']
GuidanceData = _reflection.GeneratedProtocolMessageType('GuidanceData', (_message.Message,), {
  'DESCRIPTOR' : _GUIDANCEDATA,
  '__module__' : 'proto.guidance_data_pb2'
  # @@protoc_insertion_point(class_scope:GuidanceData)
  })
_sym_db.RegisterMessage(GuidanceData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GUIDANCEDATA._serialized_start=30
  _GUIDANCEDATA._serialized_end=633
# @@protoc_insertion_point(module_scope)
