# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hms_and_cmd_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/hms_and_cmd_data.proto\"\xc7\x03\n\x07HmsData\x12\x16\n\x0e\x62\x61tteryVoltage\x18\x01 \x01(\x02\x12\x0e\n\x06nCells\x18\x02 \x01(\r\x12\'\n\x0cmainLogLevel\x18\x03 \x01(\x0e\x32\x11.HmsData.LogLevel\x12*\n\x0fsensorsLogLevel\x18\x04 \x01(\x0e\x32\x11.HmsData.LogLevel\x12&\n\x0bnavLogLevel\x18\x05 \x01(\x0e\x32\x11.HmsData.LogLevel\x12+\n\x10guidanceLogLevel\x18\x06 \x01(\x0e\x32\x11.HmsData.LogLevel\x12\x17\n\x0fnetworkTickRate\x18\x07 \x01(\r\x12\x14\n\x0cmainTickRate\x18\x08 \x01(\r\x12\x17\n\x0fsensorsTickRate\x18\t \x01(\r\x12\x18\n\x10\x63ombinedTickRate\x18\n \x01(\r\x12\x1b\n\x13longestCombinedTick\x18\x0b \x01(\r\x12\x11\n\terrorInfo\x18\x0c \x01(\t\"\'\n\x05\x45rror\x12\x0f\n\x0bLOW_BATTERY\x10\x00\x12\r\n\tWTF_AHMAD\x10\x01\"/\n\x08LogLevel\x12\n\n\x06NORMAL\x10\x00\x12\t\n\x05\x44\x45\x42UG\x10\x01\x12\x0c\n\x08OVERKILL\x10\x02\"\x8c\x03\n\x07\x43mdData\x12\x13\n\x0bplaceholder\x18\x01 \x01(\x05\x12\x11\n\tleftPower\x18\x02 \x01(\x02\x12\x12\n\nrightPower\x18\x03 \x01(\x02\x12\x11\n\tpropPower\x18\x04 \x01(\x02\x12#\n\x08runState\x18\x05 \x01(\x0e\x32\x11.CmdData.RunState\x12\'\n\x0cmainLogLevel\x18\x06 \x01(\x0e\x32\x11.HmsData.LogLevel\x12*\n\x0fsensorsLogLevel\x18\x07 \x01(\x0e\x32\x11.HmsData.LogLevel\x12&\n\x0bnavLogLevel\x18\x08 \x01(\x0e\x32\x11.HmsData.LogLevel\x12+\n\x10guidanceLogLevel\x18\t \x01(\x0e\x32\x11.HmsData.LogLevel\x12\x0e\n\x06nTraps\x18\n \x01(\r\x12\r\n\x05trapX\x18\x0b \x03(\x02\x12\r\n\x05trapY\x18\x0c \x03(\x02\"5\n\x08RunState\x12\n\n\x06\x45_STOP\x10\x00\x12\x08\n\x04\x41UTO\x10\x01\x12\n\n\x06TELEOP\x10\x02\x12\x07\n\x03SIM\x10\x03\x62\x06proto3')



_HMSDATA = DESCRIPTOR.message_types_by_name['HmsData']
_CMDDATA = DESCRIPTOR.message_types_by_name['CmdData']
_HMSDATA_ERROR = _HMSDATA.enum_types_by_name['Error']
_HMSDATA_LOGLEVEL = _HMSDATA.enum_types_by_name['LogLevel']
_CMDDATA_RUNSTATE = _CMDDATA.enum_types_by_name['RunState']
HmsData = _reflection.GeneratedProtocolMessageType('HmsData', (_message.Message,), {
  'DESCRIPTOR' : _HMSDATA,
  '__module__' : 'proto.hms_and_cmd_data_pb2'
  # @@protoc_insertion_point(class_scope:HmsData)
  })
_sym_db.RegisterMessage(HmsData)

CmdData = _reflection.GeneratedProtocolMessageType('CmdData', (_message.Message,), {
  'DESCRIPTOR' : _CMDDATA,
  '__module__' : 'proto.hms_and_cmd_data_pb2'
  # @@protoc_insertion_point(class_scope:CmdData)
  })
_sym_db.RegisterMessage(CmdData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HMSDATA._serialized_start=33
  _HMSDATA._serialized_end=488
  _HMSDATA_ERROR._serialized_start=400
  _HMSDATA_ERROR._serialized_end=439
  _HMSDATA_LOGLEVEL._serialized_start=441
  _HMSDATA_LOGLEVEL._serialized_end=488
  _CMDDATA._serialized_start=491
  _CMDDATA._serialized_end=887
  _CMDDATA_RUNSTATE._serialized_start=834
  _CMDDATA_RUNSTATE._serialized_end=887
# @@protoc_insertion_point(module_scope)
