# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/imu_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/imu_data.proto\"\x90\x01\n\x07ImuData\x12\x0e\n\x06\x61\x63\x63\x65lX\x18\x01 \x01(\x02\x12\x0e\n\x06\x61\x63\x63\x65lY\x18\x02 \x01(\x02\x12\x0e\n\x06\x61\x63\x63\x65lZ\x18\x03 \x01(\x02\x12\x0c\n\x04magX\x18\x04 \x01(\x02\x12\x0c\n\x04magY\x18\x05 \x01(\x02\x12\x0c\n\x04magZ\x18\x06 \x01(\x02\x12\r\n\x05gyroX\x18\x07 \x01(\x02\x12\r\n\x05gyroY\x18\x08 \x01(\x02\x12\r\n\x05gyroZ\x18\t \x01(\x02\x62\x06proto3')



_IMUDATA = DESCRIPTOR.message_types_by_name['ImuData']
ImuData = _reflection.GeneratedProtocolMessageType('ImuData', (_message.Message,), {
  'DESCRIPTOR' : _IMUDATA,
  '__module__' : 'proto.imu_data_pb2'
  # @@protoc_insertion_point(class_scope:ImuData)
  })
_sym_db.RegisterMessage(ImuData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMUDATA._serialized_start=25
  _IMUDATA._serialized_end=169
# @@protoc_insertion_point(module_scope)
