# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/nav_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/nav_data.proto\"\xb3\x02\n\x07NavData\x12\x0c\n\x04posX\x18\x01 \x01(\x02\x12\x0c\n\x04posY\x18\x02 \x01(\x02\x12\x0c\n\x04posZ\x18\x03 \x01(\x02\x12\x0c\n\x04velX\x18\x04 \x01(\x02\x12\x0c\n\x04velY\x18\x05 \x01(\x02\x12\x0c\n\x04velZ\x18\x06 \x01(\x02\x12\x0c\n\x04\x61\x63\x63X\x18\x07 \x01(\x02\x12\x0c\n\x04\x61\x63\x63Y\x18\x08 \x01(\x02\x12\x0c\n\x04\x61\x63\x63Z\x18\t \x01(\x02\x12\r\n\x05\x61ngXy\x18\n \x01(\x02\x12\r\n\x05\x61ngXz\x18\x0b \x01(\x02\x12\r\n\x05\x61ngYz\x18\x0c \x01(\x02\x12\x10\n\x08\x61ngVelXy\x18\r \x01(\x02\x12\x10\n\x08\x61ngVelXz\x18\x0e \x01(\x02\x12\x10\n\x08\x61ngVelYz\x18\x0f \x01(\x02\x12\x10\n\x08\x61ngAccXy\x18\x10 \x01(\x02\x12\x10\n\x08\x61ngAccXz\x18\x11 \x01(\x02\x12\x10\n\x08\x61ngAccYz\x18\x12 \x01(\x02\x12\x11\n\ttimestamp\x18\x13 \x01(\rb\x06proto3')



_NAVDATA = DESCRIPTOR.message_types_by_name['NavData']
NavData = _reflection.GeneratedProtocolMessageType('NavData', (_message.Message,), {
  'DESCRIPTOR' : _NAVDATA,
  '__module__' : 'proto.nav_data_pb2'
  # @@protoc_insertion_point(class_scope:NavData)
  })
_sym_db.RegisterMessage(NavData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NAVDATA._serialized_start=25
  _NAVDATA._serialized_end=332
# @@protoc_insertion_point(module_scope)
