# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tof_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/tof_data.proto\"(\n\x07TofData\x12\x0c\n\x04\x64ist\x18\x01 \x01(\r\x12\x0f\n\x07numObjs\x18\x02 \x01(\rb\x06proto3')



_TOFDATA = DESCRIPTOR.message_types_by_name['TofData']
TofData = _reflection.GeneratedProtocolMessageType('TofData', (_message.Message,), {
  'DESCRIPTOR' : _TOFDATA,
  '__module__' : 'proto.tof_data_pb2'
  # @@protoc_insertion_point(class_scope:TofData)
  })
_sym_db.RegisterMessage(TofData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOFDATA._serialized_start=24
  _TOFDATA._serialized_end=64
# @@protoc_insertion_point(module_scope)
