# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/tof_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/tof_data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14proto/tof_data.proto\"\x17\n\x07TofData\x12\x0c\n\x04\x64ist\x18\x01 \x01(\rb\x06proto3'
)




_TOFDATA = _descriptor.Descriptor(
  name='TofData',
  full_name='TofData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='dist', full_name='TofData.dist', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=47,
)

DESCRIPTOR.message_types_by_name['TofData'] = _TOFDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TofData = _reflection.GeneratedProtocolMessageType('TofData', (_message.Message,), {
  'DESCRIPTOR' : _TOFDATA,
  '__module__' : 'proto.tof_data_pb2'
  # @@protoc_insertion_point(class_scope:TofData)
  })
_sym_db.RegisterMessage(TofData)


# @@protoc_insertion_point(module_scope)
